# Generated by Django 2.2.6 on 2019-11-18 02:03

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('fecha_eliminacion', models.DateField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=40)),
                ('marca', models.CharField(max_length=50)),
                ('color', colorful.fields.RGBColorField(colors=['#FF0000', '#00FF00', '#0000FF'])),
                ('precio_comprar', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('numero_talla', models.CharField(max_length=40)),
                ('codigo', models.IntegerField()),
                ('tipo_tela', models.CharField(max_length=40)),
                ('descuento', models.FloatField(default=0)),
                ('imagen', models.ImageField(upload_to='')),
                ('cantidad', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
