# Generated by Django 2.2.6 on 2019-10-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=12)),
                ('precio_comprar', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('numero_talla', models.CharField(max_length=40)),
                ('codigo', models.IntegerField()),
                ('tipo_tela', models.CharField(max_length=40)),
                ('descuento', models.FloatField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
