# Generated by Django 2.2.6 on 2019-10-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedorProductos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=40),
        ),
    ]
