# Generated by Django 2.2.6 on 2019-11-01 02:52

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedorProductos', '0002_auto_20191030_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=colorful.fields.RGBColorField(colors=['#FF0000', '#00FF00', '#0000FF']),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
