# Generated by Django 2.2.6 on 2019-11-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedorProductos', '0005_auto_20191108_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.FloatField(default=0),
        ),
    ]
