# Generated by Django 2.2.6 on 2019-11-15 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=15)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('fecha_nacimiento', models.DateField()),
                ('region', models.IntegerField(choices=[(0, 'Región Metropolitana de Santiago'), (1, 'Región de Tarapacá'), (2, 'Región de Antofagasta'), (3, 'Región de Atacama'), (4, 'Región de Coquimbo'), (5, 'Región de Valparaíso'), (6, "Región del Libertador Bernardo O 'Higgins"), (7, 'Región del Maule'), (8, 'Región del Bío Bío'), (9, 'Región de la Araucanía'), (10, 'Región de los Lagos'), (11, 'Región de Aysén del General Carlos Ibáñez del Campo'), (12, 'Región de Magallanes y la Antártica Chilena'), (13, 'Región de Los Ríos'), (14, 'Región de Arica-Parinacota')], null=True)),
                ('comuna', models.CharField(choices=[('lr', 'La Reina'), ('pu', 'Pudahue')], max_length=60, null=True)),
                ('vivienda', models.IntegerField(choices=[(1, 'Casa con patio Grande'), (2, 'Casa con patio Pequeño'), (3, 'Casa sin Patio'), (4, 'Departamento')], null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
