# Generated by Django 2.2.6 on 2019-11-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedorUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
